export type Project = {
    id: string;
    title: string;
    short: string;
    image: string;
    githubUrl?: string;
    docId?: string;
    icons?: string[];
    long?: string;
};

const projects: Project[] = [
    { id: 'vserver', title: 'VServer', short: 'Vserver Setup', image: '/img/projects/vserver.png', githubUrl: 'https://github.com/reiloe/v-server-setup', docId: 'vserver', icons: ['/img/icons/linux.png', '/img/icons/security.png', '/img/icons/scripting.png'], long: 'As part of this project, I deployed and configured a virtual server to establish a secure and efficient web infrastructure. This included installing and configuring NGINX as a web server, setting up Git for version control, and implementing a passwordless SSH login using key-based authentication. Additionally, I enhanced server security by disabling remote login via username and password, allowing only SSH key authentication. This setup ensures a hardened, maintainable, and scalable server environment.' },
    { id: 'minecraft', title: 'Minecraft', short: 'Minecraft', image: '/img/projects/minecraft.png', githubUrl: 'https://github.com/reiloe/minecraft', docId: 'minecraft', icons: ['/img/icons/container.png', '/img/icons/security.png', '/img/icons/yaml.png', '/img/icons/scripting.png'], long: 'Minecraft is a creative sandbox game where players collect resources, build structures, and experience a wide variety of adventures in an open block-based world. Its flexibility, modability, and support for custom server environments make it ideal for technical experiments, automation, and server-side customization. <br>As part of a project, I deployed a Minecraft server in a Docker container and operated it on a virtual server. This included containerizing the server environment as well as configuring the network and persistence structures.' },
    { id: 'wordpress', title: 'WordPress', short: 'WordPress', image: '/img/projects/wordpress.png', githubUrl: 'https://github.com/reiloe/wordpress', docId: 'wordpress', icons: ['/img/icons/container.png', '/img/icons/security.png', '/img/icons/yaml.png'], long: 'In this project, I containerized a complete WordPress environment using Docker Compose, including both the WordPress application and a MySQL database. The setup involved defining multi-container configurations, managing environment variables, and ensuring persistent storage for database and application data. By isolating the services in separate containers, the deployment became more modular, portable, and easy to maintain. This approach provides a reproducible development and production setup with simplified updates and streamlined management.' },
    { id: 'juiceshop', title: 'OWASP', short: 'OWASP JuiceShop', image: '/img/projects/juice.png', githubUrl: 'https://github.com/reiloe/juice-shop', docId: 'juiceshop', icons: ['/img/icons/security.png', '/img/icons/linux.png', '/img/icons/scripting.png'], long: 'In this project, I created a security testing environment with a Kali Linux VM and a VM running the OWASP Juice Shop. The setup enabled hands-on practice with common web application vulnerabilities and exploitation techniques. I worked through multiple challenges, applying methods for vulnerability identification, attack execution, and security analysis. This project provided hands-on experience with pentesting workflows, common attack vectors, and core web application security concepts.' },
    { id: 'conduitcicd', title: 'Conduit CI/CD', short: 'Conduit CI/CD', image: '/img/projects/conduit-cicd.jpg', githubUrl: 'https://github.com/reiloe/conduit-cicd', docId: 'cicd', icons: ['/img/icons/container.png', '/img/icons/cicd.png', '/img/icons/yaml.png'], long: 'As part of this project, I created a GitHub workflow using GitHub Actions to automate the deployment of an application consisting of an Angular frontend and a Django backend. The workflow builds and containerizes both components, deploys them to a virtual server, and starts the application automatically. This setup enables a streamlined CI/CD process, ensuring consistent, reproducible deployments and simplified management of the application environment.' }
];

export default projects;